# Generated by Django 4.1.3 on 2022-12-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=2)),
                ('zipCode', models.CharField(default='', max_length=5)),
                ('instructions', models.TextField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
